# options for analysis running
run:
  # default concurrency is an available CPU number
  concurrency: 4

  # timeout for analysis, e.g., 30s, 5m, default is 1m
  timeout: 20m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on a full path;
  # default value is an empty list, but default dirs are skipped independently
  # of this option's value (see skip-dirs-use-default).
  skip-dirs:
    - db
    - .fleet
    - .github
    - idea

linters:
  enable:
#    - gci
    - godot
    - gofmt
    - misspell
    - whitespace
linters-settings:
  gci:
    sections:
      - standard
      - default
#      - prefix(github.com/ynachi/gcache)
